[book]
authors = ["Never Type Members"]
language = "en"
multilingual = false
src = "."
title = "Never Type initiative"

[output.html]
no-section-label=true
git-repository-url="https://github.com/rust-lang/never-type-initiative"
edit-url-template="https://github.com/rust-lang/never-type-initiative/edit/master/{path}"
site-url="/never-type-initiative/"

[output.html.fold]
enable = true
level = 0
